### PR TITLE
add rockylinux9 and ubuntu 2204 dockerfiles, without h3 support

### PR DESCRIPTION
**Pull request by traeak**

### CODE REVIEW

**Comment by bneradt** [comment]
Looks good. Why not the QUIC+HTTP/3 support though?

**Comment by traeak** [comment]
It wasn't working wrong packages and everything. I can work on that yet but
figured having and image that works is a good start

**Comment by bneradt** [comment]
> It wasn't working wrong packages and everything. I can work on that yet but figured having and image that works is a good start
> […](#)

Sounds good. Was just curious. We can work on it later. It's just that when we finally do make the switch, we must get those openssl-quic builds working, along with a curl version which has `HTTP3` support in the `--version` output.

**Comment by maskit** [comment]
It'd be great if we have BoringSSL.

**Pull request merged**
